import cx_Freeze

assets = ['assets/images/inquisitor/front/normal/1.png', 'assets/images/inquisitor/front/normal/2.png', 'assets/images/inquisitor/front/normal/3.png', 'assets/images/inquisitor/front/normal/4.png', 'assets/images/inquisitor/back/normal/1.png', 'assets/images/inquisitor/back/normal/2.png', 'assets/images/inquisitor/back/normal/3.png', 'assets/images/inquisitor/back/normal/4.png', 'assets/images/inquisitor/right/normal/1.png', 'assets/images/inquisitor/right/normal/2.png', 'assets/images/inquisitor/right/normal/3.png', 'assets/images/inquisitor/right/normal/4.png', 'assets/images/inquisitor/left/normal/1.png', 'assets/images/inquisitor/left/normal/2.png', 'assets/images/inquisitor/left/normal/3.png', 'assets/images/inquisitor/left/normal/4.png', 'assets/images/inquisitor/front/invincible/1.png', 'assets/images/inquisitor/front/invincible/2.png', 'assets/images/inquisitor/front/invincible/3.png',
 'assets/images/inquisitor/front/invincible/4.png', 'assets/images/inquisitor/back/invincible/1.png', 'assets/images/inquisitor/back/invincible/2.png', 'assets/images/inquisitor/back/invincible/3.png', 'assets/images/inquisitor/back/invincible/4.png', 'assets/images/inquisitor/right/invincible/1.png', 'assets/images/inquisitor/right/invincible/2.png', 'assets/images/inquisitor/right/invincible/3.png', 'assets/images/inquisitor/right/invincible/4.png', 'assets/images/inquisitor/left/invincible/1.png', 'assets/images/inquisitor/left/invincible/2.png', 'assets/images/inquisitor/left/invincible/3.png', 'assets/images/inquisitor/left/invincible/4.png', 'assets/images/player_attack/back/1.png', 'assets/images/player_attack/back/2.png', 'assets/images/player_attack/back/3.png', 'assets/images/player_attack/front/1.png', 'assets/images/player_attack/front/2.png', 'assets/images/player_attack/front/3.png', 'assets/images/player_attack/left/1.png', 'assets/images/player_attack/left/2.png', 'assets/images/player_attack/left/3.png', 'assets/images/player_attack/right/1.png', 'assets/images/player_attack/right/2.png', 'assets/images/player_attack/right/3.png',
  'assets/images/slime/movement/1.png', 'assets/images/slime/movement/2.png', 'assets/images/slime/death/1.png', 'assets/images/slime/damage/1.png', 'assets/images/slime/damage/2.png', 'assets/images/enemies/skull/movement/1.png', 'assets/images/enemies/skull/movement/2.png', 'assets/images/enemies/skull/damage/1.png', 'assets/images/enemies/skull/damage/2.png', 'assets/images/enemies/skull/death/1.png', 'assets/images/enemies/tar_ball/movement/1.png', 'assets/images/enemies/tar_ball/movement/2.png', 'assets/images/enemies/tar_ball/damage/1.png', 'assets/images/enemies/tar_ball/damage/2.png', 'assets/images/enemies/tar_ball/death/1.png', 'assets/images/pickups/exp/1.png', 'assets/images/pickups/exp/2.png', 'assets/images/pickups/exp/3.png', 'assets/images/pickups/exp/4.png', 'assets/images/ui/exp_left.png', 'assets/images/ui/exp_right.png', 'assets/images/ui/exp_middle.png', 'assets/images/ui/exp_fill.png', 'assets/images/ui/hud_bar.png', 'assets/images/ui/full_heart.png', 'assets/images/ui/half_heart.png', 'assets/images/ui/empty_heart.png', 'assets/images/title_background.png', 'assets/images/background_sand.png', 'assets/images/start_button.png', 'assets/images/quit_button.png', 'assets/images/try_again.png']


executables = [cx_Freeze.Executable('main.py')]

cx_Freeze.setup(
    name='Nature\'s Vengeance',
    options={'build_exe' : {'packages' : ['pygame', 'sys'], 'include_files' : assets}},
    executables = executables


)
